### ISSUE TITLE
CSS file change.

### ISSUE THREAD

**Issue by downtiser** [edublocks/edublocks#151]
Hi, Recently, I encountered a problem when porting your project. When I modified the CSS file in the original file, such as editor.css, and restarted the service, I found that the CSS file was still the original unmodified version in the browser. Could you please tell me the correct way to modify it? Thanks!

**Comment by JoshuaLowe1002** [comment]
Hi @downtiser!

Thanks for the issue, EduBlocks is undergoing a rewrite so it's probably best to hold off changing CSS and adding new features to the current project.

Thanks!
